// flow-typed signature: 8735fece322f998a39aa2742373c864b
// flow-typed version: <<STUB>>/binary-search-bounds_v^2.0.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'binary-search-bounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'binary-search-bounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'binary-search-bounds/example/example' {
  declare module.exports: any;
}

declare module 'binary-search-bounds/search-bounds' {
  declare module.exports: any;
}

declare module 'binary-search-bounds/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'binary-search-bounds/example/example.js' {
  declare module.exports: $Exports<'binary-search-bounds/example/example'>;
}
declare module 'binary-search-bounds/search-bounds.js' {
  declare module.exports: $Exports<'binary-search-bounds/search-bounds'>;
}
declare module 'binary-search-bounds/test/test.js' {
  declare module.exports: $Exports<'binary-search-bounds/test/test'>;
}
