// flow-typed signature: e6f1d92a6efcc57f3d727b5e0b81de5a
// flow-typed version: <<STUB>>/bubleify_v^1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bubleify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bubleify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bubleify/lib/Bubleify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bubleify/index' {
  declare module.exports: $Exports<'bubleify'>;
}
declare module 'bubleify/index.js' {
  declare module.exports: $Exports<'bubleify'>;
}
declare module 'bubleify/lib/Bubleify.js' {
  declare module.exports: $Exports<'bubleify/lib/Bubleify'>;
}
