// flow-typed signature: 5ffd2d87d18c408113ee842fb8d1df29
// flow-typed version: <<STUB>>/comlinkjs_v^2.3.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'comlinkjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'comlinkjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'comlinkjs/comlink.es6' {
  declare module.exports: any;
}

declare module 'comlinkjs/comlink.es6.min' {
  declare module.exports: any;
}

declare module 'comlinkjs/comlink.global' {
  declare module.exports: any;
}

declare module 'comlinkjs/comlink.global.min' {
  declare module.exports: any;
}

declare module 'comlinkjs/comlink.umd' {
  declare module.exports: any;
}

declare module 'comlinkjs/comlink.umd.min' {
  declare module.exports: any;
}

declare module 'comlinkjs/messagechanneladapter.es6' {
  declare module.exports: any;
}

declare module 'comlinkjs/messagechanneladapter.es6.min' {
  declare module.exports: any;
}

declare module 'comlinkjs/messagechanneladapter.global' {
  declare module.exports: any;
}

declare module 'comlinkjs/messagechanneladapter.global.min' {
  declare module.exports: any;
}

declare module 'comlinkjs/messagechanneladapter.umd' {
  declare module.exports: any;
}

declare module 'comlinkjs/messagechanneladapter.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'comlinkjs/comlink.es6.js' {
  declare module.exports: $Exports<'comlinkjs/comlink.es6'>;
}
declare module 'comlinkjs/comlink.es6.min.js' {
  declare module.exports: $Exports<'comlinkjs/comlink.es6.min'>;
}
declare module 'comlinkjs/comlink.global.js' {
  declare module.exports: $Exports<'comlinkjs/comlink.global'>;
}
declare module 'comlinkjs/comlink.global.min.js' {
  declare module.exports: $Exports<'comlinkjs/comlink.global.min'>;
}
declare module 'comlinkjs/comlink.umd.js' {
  declare module.exports: $Exports<'comlinkjs/comlink.umd'>;
}
declare module 'comlinkjs/comlink.umd.min.js' {
  declare module.exports: $Exports<'comlinkjs/comlink.umd.min'>;
}
declare module 'comlinkjs/messagechanneladapter.es6.js' {
  declare module.exports: $Exports<'comlinkjs/messagechanneladapter.es6'>;
}
declare module 'comlinkjs/messagechanneladapter.es6.min.js' {
  declare module.exports: $Exports<'comlinkjs/messagechanneladapter.es6.min'>;
}
declare module 'comlinkjs/messagechanneladapter.global.js' {
  declare module.exports: $Exports<'comlinkjs/messagechanneladapter.global'>;
}
declare module 'comlinkjs/messagechanneladapter.global.min.js' {
  declare module.exports: $Exports<'comlinkjs/messagechanneladapter.global.min'>;
}
declare module 'comlinkjs/messagechanneladapter.umd.js' {
  declare module.exports: $Exports<'comlinkjs/messagechanneladapter.umd'>;
}
declare module 'comlinkjs/messagechanneladapter.umd.min.js' {
  declare module.exports: $Exports<'comlinkjs/messagechanneladapter.umd.min'>;
}
