// flow-typed signature: 02fbda3239144f8dbe5a9c7bfe8415fe
// flow-typed version: <<STUB>>/datauri_v^1.0.5/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'datauri'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'datauri' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'datauri/api' {
  declare module.exports: any;
}

declare module 'datauri/module' {
  declare module.exports: any;
}

declare module 'datauri/old/api' {
  declare module.exports: any;
}

declare module 'datauri/old/module' {
  declare module.exports: any;
}

declare module 'datauri/old/template/css' {
  declare module.exports: any;
}

declare module 'datauri/old/template/uri' {
  declare module.exports: any;
}

declare module 'datauri/template/css' {
  declare module.exports: any;
}

declare module 'datauri/template/uri' {
  declare module.exports: any;
}

// Filename aliases
declare module 'datauri/api.js' {
  declare module.exports: $Exports<'datauri/api'>;
}
declare module 'datauri/index' {
  declare module.exports: $Exports<'datauri'>;
}
declare module 'datauri/index.js' {
  declare module.exports: $Exports<'datauri'>;
}
declare module 'datauri/module.js' {
  declare module.exports: $Exports<'datauri/module'>;
}
declare module 'datauri/old/api.js' {
  declare module.exports: $Exports<'datauri/old/api'>;
}
declare module 'datauri/old/module.js' {
  declare module.exports: $Exports<'datauri/old/module'>;
}
declare module 'datauri/old/template/css.js' {
  declare module.exports: $Exports<'datauri/old/template/css'>;
}
declare module 'datauri/old/template/uri.js' {
  declare module.exports: $Exports<'datauri/old/template/uri'>;
}
declare module 'datauri/template/css.js' {
  declare module.exports: $Exports<'datauri/template/css'>;
}
declare module 'datauri/template/uri.js' {
  declare module.exports: $Exports<'datauri/template/uri'>;
}
