// flow-typed signature: f67661c015b0acc931c402b1e3f48512
// flow-typed version: <<STUB>>/normalize-for-search_v^2.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-for-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-for-search' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'normalize-for-search/src/normalize' {
  declare module.exports: any;
}

declare module 'normalize-for-search/tests/normalize.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'normalize-for-search/src/normalize.js' {
  declare module.exports: $Exports<'normalize-for-search/src/normalize'>;
}
declare module 'normalize-for-search/tests/normalize.test.js' {
  declare module.exports: $Exports<'normalize-for-search/tests/normalize.test'>;
}
