// flow-typed signature: 5619e3acb5c6851b13acb9c2c05015b2
// flow-typed version: <<STUB>>/simple-concat_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-concat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-concat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-concat/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-concat/index' {
  declare module.exports: $Exports<'simple-concat'>;
}
declare module 'simple-concat/index.js' {
  declare module.exports: $Exports<'simple-concat'>;
}
declare module 'simple-concat/test/basic.js' {
  declare module.exports: $Exports<'simple-concat/test/basic'>;
}
