// flow-typed signature: 7fbc8ae096d4c8ffa73b0bc5df2f6014
// flow-typed version: <<STUB>>/webworkify_v^1.5.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webworkify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webworkify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webworkify/example/bare-blob-main' {
  declare module.exports: any;
}

declare module 'webworkify/example/bare-blob-worker' {
  declare module.exports: any;
}

declare module 'webworkify/example/main' {
  declare module.exports: any;
}

declare module 'webworkify/example/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webworkify/example/bare-blob-main.js' {
  declare module.exports: $Exports<'webworkify/example/bare-blob-main'>;
}
declare module 'webworkify/example/bare-blob-worker.js' {
  declare module.exports: $Exports<'webworkify/example/bare-blob-worker'>;
}
declare module 'webworkify/example/main.js' {
  declare module.exports: $Exports<'webworkify/example/main'>;
}
declare module 'webworkify/example/worker.js' {
  declare module.exports: $Exports<'webworkify/example/worker'>;
}
declare module 'webworkify/index' {
  declare module.exports: $Exports<'webworkify'>;
}
declare module 'webworkify/index.js' {
  declare module.exports: $Exports<'webworkify'>;
}
