// flow-typed signature: 4cf1c1e142364a8013af084e5fcd1ac9
// flow-typed version: <<STUB>>/zimmer_v^1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zimmer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zimmer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zimmer/cli' {
  declare module.exports: any;
}

declare module 'zimmer/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zimmer/cli.js' {
  declare module.exports: $Exports<'zimmer/cli'>;
}
declare module 'zimmer/index' {
  declare module.exports: $Exports<'zimmer'>;
}
declare module 'zimmer/index.js' {
  declare module.exports: $Exports<'zimmer'>;
}
declare module 'zimmer/test.js' {
  declare module.exports: $Exports<'zimmer/test'>;
}
